;;;; +----------------------------------------------------------------+
;;;; | DBUS                                               DEATH, 2010 |
;;;; +----------------------------------------------------------------+

(defpackage #:dbus
  (:use #:cl #:alexandria #:split-sequence)
  (:export
   #:dbus-error
   #:inexistent-entry
   #:inexistent-entry-designator
   #:entry-replacement-attempt
   #:entry-replacement-attempt-old
   #:entry-replacement-attempt-new
   #:server-address
   #:connection
   #:authentication-mechanism
   #:server-address-transport-name
   #:server-address-property
   #:open-connection
   #:connection-server-address
   #:connection-server-uuid
   #:connection-fd
   #:connection-pending-messages
   #:connection-next-serial
   #:drain-pending-messages
   #:close-connection
   #:wait-for-reply
   #:receive-message
   #:receive-line
   #:send-message
   #:send-line
   #:authentication-mechanism-name
   #:authentication-mechanism-textual-p
   #:feed-authentication-mechanism
   #:supported-authentication-mechanisms
   #:authenticate
   #:find-server-address-class
   #:find-authentication-mechanism-class
   #:with-open-connection
   #:standard-server-address
   #:generic-server-address
   #:parse-server-addresses-string
   #:session-server-addresses
   #:system-server-addresses
   #:standard-connection
   #:socket-connection-mixin
   #:open-socket-connection
   #:standard-authentication-mechanism
   #:generic-authentication-mechanism
   #:authentication-error
   #:authentication-error-command
   #:authentication-error-argument
   #:unix-server-address
   #:unix-connection
   #:dbus-cookie-sha1-authentication-mechanism
   #:signature
   #:sigexp
   #:pack
   #:unpack
   #:encode-message
   #:message
   #:standard-message
   #:message-endianness
   #:message-flags
   #:message-major-protocol-version
   #:message-body-length
   #:message-serial
   #:message-destination
   #:message-sender
   #:message-signature
   #:message-body
   #:method-call-message
   #:message-path
   #:message-interface
   #:message-member
   #:signal-message
   #:method-return-message
   #:message-reply-serial
   #:error-message
   #:message-error-name
   #:decode-message
   #:invoke-method))
